// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GAME.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GAME.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace GAME {
class CS_PINGDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CS_PING> {
} _CS_PING_default_instance_;
class SC_PINGDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SC_PING> {
} _SC_PING_default_instance_;
class CS_ENTER_FIELDDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CS_ENTER_FIELD> {
} _CS_ENTER_FIELD_default_instance_;
class SC_ENTER_FIELDDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SC_ENTER_FIELD> {
} _SC_ENTER_FIELD_default_instance_;

namespace protobuf_GAME_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[4];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CS_PING, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CS_PING, timestamp_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_PING, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_PING, timestamp_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CS_ENTER_FIELD, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CS_ENTER_FIELD, field_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_ENTER_FIELD, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_ENTER_FIELD, result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_ENTER_FIELD, field_id_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CS_PING)},
  { 6, -1, sizeof(SC_PING)},
  { 12, -1, sizeof(CS_ENTER_FIELD)},
  { 18, -1, sizeof(SC_ENTER_FIELD)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CS_PING_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SC_PING_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_CS_ENTER_FIELD_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SC_ENTER_FIELD_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "GAME.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

}  // namespace

void TableStruct::Shutdown() {
  _CS_PING_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _SC_PING_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _CS_ENTER_FIELD_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _SC_ENTER_FIELD_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CS_PING_default_instance_.DefaultConstruct();
  _SC_PING_default_instance_.DefaultConstruct();
  _CS_ENTER_FIELD_default_instance_.DefaultConstruct();
  _SC_ENTER_FIELD_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\nGAME.proto\022\004GAME\"\034\n\007CS_PING\022\021\n\ttimesta"
      "mp\030\001 \001(\003\"\034\n\007SC_PING\022\021\n\ttimestamp\030\001 \001(\003\"\""
      "\n\016CS_ENTER_FIELD\022\020\n\010field_id\030\001 \001(\005\"2\n\016SC"
      "_ENTER_FIELD\022\016\n\006result\030\001 \001(\010\022\020\n\010field_id"
      "\030\002 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 174);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GAME.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_GAME_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CS_PING::kTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CS_PING::CS_PING()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_GAME_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:GAME.CS_PING)
}
CS_PING::CS_PING(const CS_PING& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:GAME.CS_PING)
}

void CS_PING::SharedCtor() {
  timestamp_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

CS_PING::~CS_PING() {
  // @@protoc_insertion_point(destructor:GAME.CS_PING)
  SharedDtor();
}

void CS_PING::SharedDtor() {
}

void CS_PING::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CS_PING::descriptor() {
  protobuf_GAME_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GAME_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CS_PING& CS_PING::default_instance() {
  protobuf_GAME_2eproto::InitDefaults();
  return *internal_default_instance();
}

CS_PING* CS_PING::New(::google::protobuf::Arena* arena) const {
  CS_PING* n = new CS_PING;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CS_PING::Clear() {
// @@protoc_insertion_point(message_clear_start:GAME.CS_PING)
  timestamp_ = GOOGLE_LONGLONG(0);
}

bool CS_PING::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GAME.CS_PING)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GAME.CS_PING)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GAME.CS_PING)
  return false;
#undef DO_
}

void CS_PING::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GAME.CS_PING)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->timestamp(), output);
  }

  // @@protoc_insertion_point(serialize_end:GAME.CS_PING)
}

::google::protobuf::uint8* CS_PING::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:GAME.CS_PING)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->timestamp(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:GAME.CS_PING)
  return target;
}

size_t CS_PING::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GAME.CS_PING)
  size_t total_size = 0;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CS_PING::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GAME.CS_PING)
  GOOGLE_DCHECK_NE(&from, this);
  const CS_PING* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CS_PING>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GAME.CS_PING)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GAME.CS_PING)
    MergeFrom(*source);
  }
}

void CS_PING::MergeFrom(const CS_PING& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GAME.CS_PING)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void CS_PING::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GAME.CS_PING)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CS_PING::CopyFrom(const CS_PING& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GAME.CS_PING)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_PING::IsInitialized() const {
  return true;
}

void CS_PING::Swap(CS_PING* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CS_PING::InternalSwap(CS_PING* other) {
  std::swap(timestamp_, other->timestamp_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CS_PING::GetMetadata() const {
  protobuf_GAME_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GAME_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CS_PING

// int64 timestamp = 1;
void CS_PING::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 CS_PING::timestamp() const {
  // @@protoc_insertion_point(field_get:GAME.CS_PING.timestamp)
  return timestamp_;
}
void CS_PING::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:GAME.CS_PING.timestamp)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SC_PING::kTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SC_PING::SC_PING()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_GAME_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:GAME.SC_PING)
}
SC_PING::SC_PING(const SC_PING& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:GAME.SC_PING)
}

void SC_PING::SharedCtor() {
  timestamp_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

SC_PING::~SC_PING() {
  // @@protoc_insertion_point(destructor:GAME.SC_PING)
  SharedDtor();
}

void SC_PING::SharedDtor() {
}

void SC_PING::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SC_PING::descriptor() {
  protobuf_GAME_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GAME_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SC_PING& SC_PING::default_instance() {
  protobuf_GAME_2eproto::InitDefaults();
  return *internal_default_instance();
}

SC_PING* SC_PING::New(::google::protobuf::Arena* arena) const {
  SC_PING* n = new SC_PING;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SC_PING::Clear() {
// @@protoc_insertion_point(message_clear_start:GAME.SC_PING)
  timestamp_ = GOOGLE_LONGLONG(0);
}

bool SC_PING::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GAME.SC_PING)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GAME.SC_PING)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GAME.SC_PING)
  return false;
#undef DO_
}

void SC_PING::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GAME.SC_PING)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->timestamp(), output);
  }

  // @@protoc_insertion_point(serialize_end:GAME.SC_PING)
}

::google::protobuf::uint8* SC_PING::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:GAME.SC_PING)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->timestamp(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:GAME.SC_PING)
  return target;
}

size_t SC_PING::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GAME.SC_PING)
  size_t total_size = 0;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SC_PING::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GAME.SC_PING)
  GOOGLE_DCHECK_NE(&from, this);
  const SC_PING* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SC_PING>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GAME.SC_PING)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GAME.SC_PING)
    MergeFrom(*source);
  }
}

void SC_PING::MergeFrom(const SC_PING& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GAME.SC_PING)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void SC_PING::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GAME.SC_PING)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SC_PING::CopyFrom(const SC_PING& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GAME.SC_PING)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SC_PING::IsInitialized() const {
  return true;
}

void SC_PING::Swap(SC_PING* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SC_PING::InternalSwap(SC_PING* other) {
  std::swap(timestamp_, other->timestamp_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SC_PING::GetMetadata() const {
  protobuf_GAME_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GAME_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SC_PING

// int64 timestamp = 1;
void SC_PING::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 SC_PING::timestamp() const {
  // @@protoc_insertion_point(field_get:GAME.SC_PING.timestamp)
  return timestamp_;
}
void SC_PING::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:GAME.SC_PING.timestamp)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CS_ENTER_FIELD::kFieldIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CS_ENTER_FIELD::CS_ENTER_FIELD()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_GAME_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:GAME.CS_ENTER_FIELD)
}
CS_ENTER_FIELD::CS_ENTER_FIELD(const CS_ENTER_FIELD& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  field_id_ = from.field_id_;
  // @@protoc_insertion_point(copy_constructor:GAME.CS_ENTER_FIELD)
}

void CS_ENTER_FIELD::SharedCtor() {
  field_id_ = 0;
  _cached_size_ = 0;
}

CS_ENTER_FIELD::~CS_ENTER_FIELD() {
  // @@protoc_insertion_point(destructor:GAME.CS_ENTER_FIELD)
  SharedDtor();
}

void CS_ENTER_FIELD::SharedDtor() {
}

void CS_ENTER_FIELD::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CS_ENTER_FIELD::descriptor() {
  protobuf_GAME_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GAME_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CS_ENTER_FIELD& CS_ENTER_FIELD::default_instance() {
  protobuf_GAME_2eproto::InitDefaults();
  return *internal_default_instance();
}

CS_ENTER_FIELD* CS_ENTER_FIELD::New(::google::protobuf::Arena* arena) const {
  CS_ENTER_FIELD* n = new CS_ENTER_FIELD;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CS_ENTER_FIELD::Clear() {
// @@protoc_insertion_point(message_clear_start:GAME.CS_ENTER_FIELD)
  field_id_ = 0;
}

bool CS_ENTER_FIELD::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GAME.CS_ENTER_FIELD)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 field_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &field_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GAME.CS_ENTER_FIELD)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GAME.CS_ENTER_FIELD)
  return false;
#undef DO_
}

void CS_ENTER_FIELD::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GAME.CS_ENTER_FIELD)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 field_id = 1;
  if (this->field_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->field_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:GAME.CS_ENTER_FIELD)
}

::google::protobuf::uint8* CS_ENTER_FIELD::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:GAME.CS_ENTER_FIELD)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 field_id = 1;
  if (this->field_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->field_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:GAME.CS_ENTER_FIELD)
  return target;
}

size_t CS_ENTER_FIELD::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GAME.CS_ENTER_FIELD)
  size_t total_size = 0;

  // int32 field_id = 1;
  if (this->field_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->field_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CS_ENTER_FIELD::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GAME.CS_ENTER_FIELD)
  GOOGLE_DCHECK_NE(&from, this);
  const CS_ENTER_FIELD* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CS_ENTER_FIELD>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GAME.CS_ENTER_FIELD)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GAME.CS_ENTER_FIELD)
    MergeFrom(*source);
  }
}

void CS_ENTER_FIELD::MergeFrom(const CS_ENTER_FIELD& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GAME.CS_ENTER_FIELD)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.field_id() != 0) {
    set_field_id(from.field_id());
  }
}

void CS_ENTER_FIELD::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GAME.CS_ENTER_FIELD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CS_ENTER_FIELD::CopyFrom(const CS_ENTER_FIELD& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GAME.CS_ENTER_FIELD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_ENTER_FIELD::IsInitialized() const {
  return true;
}

void CS_ENTER_FIELD::Swap(CS_ENTER_FIELD* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CS_ENTER_FIELD::InternalSwap(CS_ENTER_FIELD* other) {
  std::swap(field_id_, other->field_id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CS_ENTER_FIELD::GetMetadata() const {
  protobuf_GAME_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GAME_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CS_ENTER_FIELD

// int32 field_id = 1;
void CS_ENTER_FIELD::clear_field_id() {
  field_id_ = 0;
}
::google::protobuf::int32 CS_ENTER_FIELD::field_id() const {
  // @@protoc_insertion_point(field_get:GAME.CS_ENTER_FIELD.field_id)
  return field_id_;
}
void CS_ENTER_FIELD::set_field_id(::google::protobuf::int32 value) {
  
  field_id_ = value;
  // @@protoc_insertion_point(field_set:GAME.CS_ENTER_FIELD.field_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SC_ENTER_FIELD::kResultFieldNumber;
const int SC_ENTER_FIELD::kFieldIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SC_ENTER_FIELD::SC_ENTER_FIELD()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_GAME_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:GAME.SC_ENTER_FIELD)
}
SC_ENTER_FIELD::SC_ENTER_FIELD(const SC_ENTER_FIELD& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&result_, &from.result_,
    reinterpret_cast<char*>(&field_id_) -
    reinterpret_cast<char*>(&result_) + sizeof(field_id_));
  // @@protoc_insertion_point(copy_constructor:GAME.SC_ENTER_FIELD)
}

void SC_ENTER_FIELD::SharedCtor() {
  ::memset(&result_, 0, reinterpret_cast<char*>(&field_id_) -
    reinterpret_cast<char*>(&result_) + sizeof(field_id_));
  _cached_size_ = 0;
}

SC_ENTER_FIELD::~SC_ENTER_FIELD() {
  // @@protoc_insertion_point(destructor:GAME.SC_ENTER_FIELD)
  SharedDtor();
}

void SC_ENTER_FIELD::SharedDtor() {
}

void SC_ENTER_FIELD::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SC_ENTER_FIELD::descriptor() {
  protobuf_GAME_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GAME_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SC_ENTER_FIELD& SC_ENTER_FIELD::default_instance() {
  protobuf_GAME_2eproto::InitDefaults();
  return *internal_default_instance();
}

SC_ENTER_FIELD* SC_ENTER_FIELD::New(::google::protobuf::Arena* arena) const {
  SC_ENTER_FIELD* n = new SC_ENTER_FIELD;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SC_ENTER_FIELD::Clear() {
// @@protoc_insertion_point(message_clear_start:GAME.SC_ENTER_FIELD)
  ::memset(&result_, 0, reinterpret_cast<char*>(&field_id_) -
    reinterpret_cast<char*>(&result_) + sizeof(field_id_));
}

bool SC_ENTER_FIELD::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GAME.SC_ENTER_FIELD)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 field_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &field_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GAME.SC_ENTER_FIELD)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GAME.SC_ENTER_FIELD)
  return false;
#undef DO_
}

void SC_ENTER_FIELD::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GAME.SC_ENTER_FIELD)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->result(), output);
  }

  // int32 field_id = 2;
  if (this->field_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->field_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:GAME.SC_ENTER_FIELD)
}

::google::protobuf::uint8* SC_ENTER_FIELD::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:GAME.SC_ENTER_FIELD)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->result(), target);
  }

  // int32 field_id = 2;
  if (this->field_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->field_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:GAME.SC_ENTER_FIELD)
  return target;
}

size_t SC_ENTER_FIELD::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GAME.SC_ENTER_FIELD)
  size_t total_size = 0;

  // bool result = 1;
  if (this->result() != 0) {
    total_size += 1 + 1;
  }

  // int32 field_id = 2;
  if (this->field_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->field_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SC_ENTER_FIELD::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GAME.SC_ENTER_FIELD)
  GOOGLE_DCHECK_NE(&from, this);
  const SC_ENTER_FIELD* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SC_ENTER_FIELD>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GAME.SC_ENTER_FIELD)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GAME.SC_ENTER_FIELD)
    MergeFrom(*source);
  }
}

void SC_ENTER_FIELD::MergeFrom(const SC_ENTER_FIELD& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GAME.SC_ENTER_FIELD)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.result() != 0) {
    set_result(from.result());
  }
  if (from.field_id() != 0) {
    set_field_id(from.field_id());
  }
}

void SC_ENTER_FIELD::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GAME.SC_ENTER_FIELD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SC_ENTER_FIELD::CopyFrom(const SC_ENTER_FIELD& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GAME.SC_ENTER_FIELD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SC_ENTER_FIELD::IsInitialized() const {
  return true;
}

void SC_ENTER_FIELD::Swap(SC_ENTER_FIELD* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SC_ENTER_FIELD::InternalSwap(SC_ENTER_FIELD* other) {
  std::swap(result_, other->result_);
  std::swap(field_id_, other->field_id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SC_ENTER_FIELD::GetMetadata() const {
  protobuf_GAME_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_GAME_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SC_ENTER_FIELD

// bool result = 1;
void SC_ENTER_FIELD::clear_result() {
  result_ = false;
}
bool SC_ENTER_FIELD::result() const {
  // @@protoc_insertion_point(field_get:GAME.SC_ENTER_FIELD.result)
  return result_;
}
void SC_ENTER_FIELD::set_result(bool value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:GAME.SC_ENTER_FIELD.result)
}

// int32 field_id = 2;
void SC_ENTER_FIELD::clear_field_id() {
  field_id_ = 0;
}
::google::protobuf::int32 SC_ENTER_FIELD::field_id() const {
  // @@protoc_insertion_point(field_get:GAME.SC_ENTER_FIELD.field_id)
  return field_id_;
}
void SC_ENTER_FIELD::set_field_id(::google::protobuf::int32 value) {
  
  field_id_ = value;
  // @@protoc_insertion_point(field_set:GAME.SC_ENTER_FIELD.field_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace GAME

// @@protoc_insertion_point(global_scope)
